FROM golang:1.25.0-alpine

WORKDIR /app

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.26.0

COPY migrations/ /migrations/

CMD ["sh", "-ec", "test -n \"$DATABASE_URL\"; /go/bin/goose -dir /migrations postgres \"$DATABASE_URL\" up"]
