// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authorization.sql

package sqlc

import (
	"context"
)

const listActiveDivisionIDsByUser = `-- name: ListActiveDivisionIDsByUser :many
SELECT DISTINCT
    p.division_id
FROM memberships m
JOIN positions p ON p.id = m.position_id
JOIN divisions d ON d.id = p.division_id
WHERE m.user_id = $1
  AND p.is_archived = false
  AND d.is_archived = false
ORDER BY p.division_id
`

func (q *Queries) ListActiveDivisionIDsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveDivisionIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var division_id string
		if err := rows.Scan(&division_id); err != nil {
			return nil, err
		}
		items = append(items, division_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionContextsByUser = `-- name: ListPermissionContextsByUser :many
SELECT
    p.division_id,
    r.permissions
FROM memberships m
JOIN positions p ON p.id = m.position_id
JOIN roles r ON r.id = p.role_id
JOIN divisions d ON d.id = p.division_id
WHERE m.user_id = $1
  AND p.is_archived = false
  AND d.is_archived = false
`

type ListPermissionContextsByUserRow struct {
	DivisionID  string `json:"division_id"`
	Permissions []byte `json:"permissions"`
}

func (q *Queries) ListPermissionContextsByUser(ctx context.Context, userID string) ([]ListPermissionContextsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPermissionContextsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionContextsByUserRow
	for rows.Next() {
		var i ListPermissionContextsByUserRow
		if err := rows.Scan(&i.DivisionID, &i.Permissions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
