// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: divisions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveChildDivisionsByRoot = `-- name: ArchiveChildDivisionsByRoot :execrows
WITH RECURSIVE subtree AS (
    SELECT d.id
    FROM divisions d
    WHERE d.id = $1
  UNION ALL
    SELECT d.id
    FROM divisions d
    JOIN subtree s ON d.parent_id = s.id
)
UPDATE divisions
SET is_archived = true,
    updated_at = now()
WHERE divisions.id <> $1
  AND EXISTS (
      SELECT 1
      FROM subtree
      WHERE subtree.id = divisions.id
  )
  AND divisions.is_archived = false
`

func (q *Queries) ArchiveChildDivisionsByRoot(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, archiveChildDivisionsByRoot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveDivisionByID = `-- name: ArchiveDivisionByID :execrows
UPDATE divisions
SET is_archived = true,
    updated_at = now()
WHERE id = $1
  AND is_archived = false
`

func (q *Queries) ArchiveDivisionByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, archiveDivisionByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDivision = `-- name: CreateDivision :one
INSERT INTO divisions (
    id,
    parent_id,
    short_name,
    full_name,
    description,
    regulation_url,
    media_links,
    is_archived
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id,
    parent_id,
    short_name,
    full_name,
    description,
    regulation_url,
    media_links,
    is_archived,
    created_at,
    updated_at
`

type CreateDivisionParams struct {
	ID            string      `json:"id"`
	ParentID      pgtype.Text `json:"parent_id"`
	ShortName     string      `json:"short_name"`
	FullName      string      `json:"full_name"`
	Description   string      `json:"description"`
	RegulationUrl string      `json:"regulation_url"`
	MediaLinks    []byte      `json:"media_links"`
	IsArchived    bool        `json:"is_archived"`
}

func (q *Queries) CreateDivision(ctx context.Context, arg CreateDivisionParams) (Division, error) {
	row := q.db.QueryRow(ctx, createDivision,
		arg.ID,
		arg.ParentID,
		arg.ShortName,
		arg.FullName,
		arg.Description,
		arg.RegulationUrl,
		arg.MediaLinks,
		arg.IsArchived,
	)
	var i Division
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ShortName,
		&i.FullName,
		&i.Description,
		&i.RegulationUrl,
		&i.MediaLinks,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDivisionAncestors = `-- name: GetDivisionAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT
        parent.id,
        parent.parent_id,
        1::int AS depth
    FROM divisions d
    JOIN divisions parent ON parent.id = d.parent_id
    WHERE d.id = $1
  UNION ALL
    SELECT
        parent.id,
        parent.parent_id,
        a.depth + 1
    FROM ancestors a
    JOIN divisions parent ON parent.id = a.parent_id
)
SELECT id, depth
FROM ancestors
ORDER BY depth
`

type GetDivisionAncestorsRow struct {
	ID    string `json:"id"`
	Depth int32  `json:"depth"`
}

func (q *Queries) GetDivisionAncestors(ctx context.Context, id string) ([]GetDivisionAncestorsRow, error) {
	rows, err := q.db.Query(ctx, getDivisionAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDivisionAncestorsRow
	for rows.Next() {
		var i GetDivisionAncestorsRow
		if err := rows.Scan(&i.ID, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDivisionArchivedFlag = `-- name: GetDivisionArchivedFlag :one
SELECT is_archived
FROM divisions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDivisionArchivedFlag(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, getDivisionArchivedFlag, id)
	var is_archived bool
	err := row.Scan(&is_archived)
	return is_archived, err
}

const getDivisionByID = `-- name: GetDivisionByID :one
SELECT
    id,
    parent_id,
    short_name,
    full_name,
    description,
    regulation_url,
    media_links,
    is_archived,
    created_at,
    updated_at
FROM divisions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDivisionByID(ctx context.Context, id string) (Division, error) {
	row := q.db.QueryRow(ctx, getDivisionByID, id)
	var i Division
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ShortName,
		&i.FullName,
		&i.Description,
		&i.RegulationUrl,
		&i.MediaLinks,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRootDivision = `-- name: GetRootDivision :one
SELECT
    id,
    parent_id,
    short_name,
    full_name,
    description,
    regulation_url,
    media_links,
    is_archived,
    created_at,
    updated_at
FROM divisions
WHERE parent_id IS NULL
LIMIT 1
`

func (q *Queries) GetRootDivision(ctx context.Context) (Division, error) {
	row := q.db.QueryRow(ctx, getRootDivision)
	var i Division
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ShortName,
		&i.FullName,
		&i.Description,
		&i.RegulationUrl,
		&i.MediaLinks,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDivisionChildrenByParent = `-- name: ListDivisionChildrenByParent :many
SELECT
    d.id,
    d.parent_id,
    d.short_name,
    d.full_name,
    d.description,
    d.regulation_url,
    d.media_links,
    d.is_archived,
    d.created_at,
    d.updated_at,
    EXISTS (
        SELECT 1 FROM divisions c WHERE c.parent_id = d.id AND c.is_archived = false
    )::bool AS has_children,
    (
        SELECT COUNT(*)::int FROM divisions c WHERE c.parent_id = d.id AND c.is_archived = false
    ) AS children_count
FROM divisions d
WHERE d.parent_id = $1
  AND d.is_archived = false
ORDER BY d.short_name, d.id
`

type ListDivisionChildrenByParentRow struct {
	ID            string             `json:"id"`
	ParentID      pgtype.Text        `json:"parent_id"`
	ShortName     string             `json:"short_name"`
	FullName      string             `json:"full_name"`
	Description   string             `json:"description"`
	RegulationUrl string             `json:"regulation_url"`
	MediaLinks    []byte             `json:"media_links"`
	IsArchived    bool               `json:"is_archived"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	HasChildren   bool               `json:"has_children"`
	ChildrenCount int32              `json:"children_count"`
}

func (q *Queries) ListDivisionChildrenByParent(ctx context.Context, parentID pgtype.Text) ([]ListDivisionChildrenByParentRow, error) {
	rows, err := q.db.Query(ctx, listDivisionChildrenByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDivisionChildrenByParentRow
	for rows.Next() {
		var i ListDivisionChildrenByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ShortName,
			&i.FullName,
			&i.Description,
			&i.RegulationUrl,
			&i.MediaLinks,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasChildren,
			&i.ChildrenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDivisionSubtree = `-- name: ListDivisionSubtree :many
WITH RECURSIVE subtree AS (
    SELECT
        d.id,
        d.parent_id,
        0::int AS depth
    FROM divisions d
    WHERE d.id = $1
  UNION ALL
    SELECT
        d.id,
        d.parent_id,
        s.depth + 1
    FROM divisions d
    JOIN subtree s ON d.parent_id = s.id
)
SELECT
    d.id,
    d.parent_id,
    d.short_name,
    d.full_name,
    d.description,
    d.regulation_url,
    d.media_links,
    d.is_archived,
    d.created_at,
    d.updated_at,
    s.depth
FROM divisions d
JOIN subtree s ON s.id = d.id
ORDER BY s.depth DESC, d.id
`

type ListDivisionSubtreeRow struct {
	ID            string             `json:"id"`
	ParentID      pgtype.Text        `json:"parent_id"`
	ShortName     string             `json:"short_name"`
	FullName      string             `json:"full_name"`
	Description   string             `json:"description"`
	RegulationUrl string             `json:"regulation_url"`
	MediaLinks    []byte             `json:"media_links"`
	IsArchived    bool               `json:"is_archived"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Depth         int32              `json:"depth"`
}

func (q *Queries) ListDivisionSubtree(ctx context.Context, id string) ([]ListDivisionSubtreeRow, error) {
	rows, err := q.db.Query(ctx, listDivisionSubtree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDivisionSubtreeRow
	for rows.Next() {
		var i ListDivisionSubtreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ShortName,
			&i.FullName,
			&i.Description,
			&i.RegulationUrl,
			&i.MediaLinks,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDivisionTree = `-- name: ListDivisionTree :many
WITH RECURSIVE division_tree AS (
    SELECT
        id,
        parent_id,
        short_name,
        full_name,
        description,
        regulation_url,
        media_links,
        is_archived,
        created_at,
        updated_at,
        1::int AS depth
    FROM divisions
    WHERE parent_id IS NULL
      AND ($1::boolean = true OR is_archived = false)
  UNION ALL
    SELECT
        d.id,
        d.parent_id,
        d.short_name,
        d.full_name,
        d.description,
        d.regulation_url,
        d.media_links,
        d.is_archived,
        d.created_at,
        d.updated_at,
        dt.depth + 1
    FROM divisions d
    JOIN division_tree dt ON dt.id = d.parent_id
    WHERE ($1::boolean = true OR d.is_archived = false)
)
SELECT
    id,
    parent_id,
    short_name,
    full_name,
    description,
    regulation_url,
    media_links,
    is_archived,
    created_at,
    updated_at,
    depth,
    (SELECT COUNT(*)::int FROM positions WHERE positions.division_id = division_tree.id AND positions.is_archived = false) AS positions_count,
    (
        SELECT COUNT(DISTINCT m.user_id)
        FROM memberships m
        JOIN positions p ON p.id = m.position_id
        WHERE p.division_id = division_tree.id
          AND p.is_archived = false
    ) AS members_count
FROM division_tree
ORDER BY depth, parent_id, short_name, id
`

type ListDivisionTreeRow struct {
	ID             string             `json:"id"`
	ParentID       pgtype.Text        `json:"parent_id"`
	ShortName      string             `json:"short_name"`
	FullName       string             `json:"full_name"`
	Description    string             `json:"description"`
	RegulationUrl  string             `json:"regulation_url"`
	MediaLinks     []byte             `json:"media_links"`
	IsArchived     bool               `json:"is_archived"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Depth          int32              `json:"depth"`
	PositionsCount int32              `json:"positions_count"`
	MembersCount   int64              `json:"members_count"`
}

func (q *Queries) ListDivisionTree(ctx context.Context, includeArchived bool) ([]ListDivisionTreeRow, error) {
	rows, err := q.db.Query(ctx, listDivisionTree, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDivisionTreeRow
	for rows.Next() {
		var i ListDivisionTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ShortName,
			&i.FullName,
			&i.Description,
			&i.RegulationUrl,
			&i.MediaLinks,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Depth,
			&i.PositionsCount,
			&i.MembersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootDivisions = `-- name: ListRootDivisions :many
SELECT
    d.id,
    d.parent_id,
    d.short_name,
    d.full_name,
    d.description,
    d.regulation_url,
    d.media_links,
    d.is_archived,
    d.created_at,
    d.updated_at,
    EXISTS (
        SELECT 1 FROM divisions c WHERE c.parent_id = d.id AND c.is_archived = false
    )::bool AS has_children,
    (
        SELECT COUNT(*)::int FROM divisions c WHERE c.parent_id = d.id AND c.is_archived = false
    ) AS children_count
FROM divisions d
WHERE d.parent_id IS NULL
  AND d.is_archived = false
ORDER BY d.short_name, d.id
`

type ListRootDivisionsRow struct {
	ID            string             `json:"id"`
	ParentID      pgtype.Text        `json:"parent_id"`
	ShortName     string             `json:"short_name"`
	FullName      string             `json:"full_name"`
	Description   string             `json:"description"`
	RegulationUrl string             `json:"regulation_url"`
	MediaLinks    []byte             `json:"media_links"`
	IsArchived    bool               `json:"is_archived"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	HasChildren   bool               `json:"has_children"`
	ChildrenCount int32              `json:"children_count"`
}

func (q *Queries) ListRootDivisions(ctx context.Context) ([]ListRootDivisionsRow, error) {
	rows, err := q.db.Query(ctx, listRootDivisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRootDivisionsRow
	for rows.Next() {
		var i ListRootDivisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ShortName,
			&i.FullName,
			&i.Description,
			&i.RegulationUrl,
			&i.MediaLinks,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasChildren,
			&i.ChildrenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDivision = `-- name: UpdateDivision :one
UPDATE divisions
SET
    parent_id = $2,
    short_name = $3,
    full_name = $4,
    description = $5,
    regulation_url = $6,
    media_links = $7,
    is_archived = $8,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    parent_id,
    short_name,
    full_name,
    description,
    regulation_url,
    media_links,
    is_archived,
    created_at,
    updated_at
`

type UpdateDivisionParams struct {
	ID            string      `json:"id"`
	ParentID      pgtype.Text `json:"parent_id"`
	ShortName     string      `json:"short_name"`
	FullName      string      `json:"full_name"`
	Description   string      `json:"description"`
	RegulationUrl string      `json:"regulation_url"`
	MediaLinks    []byte      `json:"media_links"`
	IsArchived    bool        `json:"is_archived"`
}

func (q *Queries) UpdateDivision(ctx context.Context, arg UpdateDivisionParams) (Division, error) {
	row := q.db.QueryRow(ctx, updateDivision,
		arg.ID,
		arg.ParentID,
		arg.ShortName,
		arg.FullName,
		arg.Description,
		arg.RegulationUrl,
		arg.MediaLinks,
		arg.IsArchived,
	)
	var i Division
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ShortName,
		&i.FullName,
		&i.Description,
		&i.RegulationUrl,
		&i.MediaLinks,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
