// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: eventlog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventLog = `-- name: CountEventLog :one
SELECT count(*)
FROM event_log
WHERE ($1::text IS NULL OR event_type = $1::text)
  AND ($2::text IS NULL OR subject_type = $2::text)
  AND ($3::text IS NULL OR subject_id = $3::text)
`

type CountEventLogParams struct {
	EventType   pgtype.Text `json:"event_type"`
	SubjectType pgtype.Text `json:"subject_type"`
	SubjectID   pgtype.Text `json:"subject_id"`
}

func (q *Queries) CountEventLog(ctx context.Context, arg CountEventLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventLog, arg.EventType, arg.SubjectType, arg.SubjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEventLog = `-- name: InsertEventLog :one
INSERT INTO event_log (
    id,
    event_type,
    actor_id,
    subject_type,
    subject_id,
    payload,
    timestamp
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::jsonb,
    $7::timestamptz
)
RETURNING id, event_type, actor_id, subject_type, subject_id, payload, timestamp, created_at
`

type InsertEventLogParams struct {
	ID          string             `json:"id"`
	EventType   string             `json:"event_type"`
	ActorID     string             `json:"actor_id"`
	SubjectType string             `json:"subject_type"`
	SubjectID   string             `json:"subject_id"`
	Payload     []byte             `json:"payload"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) InsertEventLog(ctx context.Context, arg InsertEventLogParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, insertEventLog,
		arg.ID,
		arg.EventType,
		arg.ActorID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Payload,
		arg.Timestamp,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ActorID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Payload,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const listEventLog = `-- name: ListEventLog :many
SELECT id, event_type, actor_id, subject_type, subject_id, payload, timestamp, created_at
FROM event_log
WHERE ($1::text IS NULL OR event_type = $1::text)
  AND ($2::text IS NULL OR subject_type = $2::text)
  AND ($3::text IS NULL OR subject_id = $3::text)
ORDER BY timestamp DESC, id DESC
LIMIT $5::int
OFFSET $4::int
`

type ListEventLogParams struct {
	EventType   pgtype.Text `json:"event_type"`
	SubjectType pgtype.Text `json:"subject_type"`
	SubjectID   pgtype.Text `json:"subject_id"`
	PageOffset  int32       `json:"page_offset"`
	PageLimit   int32       `json:"page_limit"`
}

func (q *Queries) ListEventLog(ctx context.Context, arg ListEventLogParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, listEventLog,
		arg.EventType,
		arg.SubjectType,
		arg.SubjectID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLog
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Payload,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
