// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: memberships.sql

package sqlc

import (
	"context"
)

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (user_id, position_id) VALUES ($1, $2)
`

type CreateMembershipParams struct {
	UserID     string `json:"user_id"`
	PositionID string `json:"position_id"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.UserID, arg.PositionID)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE user_id = $1 AND position_id = $2
`

type DeleteMembershipParams struct {
	UserID     string `json:"user_id"`
	PositionID string `json:"position_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.PositionID)
	return err
}

const deleteMembershipsByDivisionSubtree = `-- name: DeleteMembershipsByDivisionSubtree :execrows
WITH RECURSIVE subtree AS (
    SELECT d.id
    FROM divisions d
    WHERE d.id = $1
  UNION ALL
    SELECT d.id
    FROM divisions d
    JOIN subtree s ON d.parent_id = s.id
)
DELETE FROM memberships m
USING positions p
WHERE m.position_id = p.id
  AND p.division_id IN (SELECT id FROM subtree)
`

func (q *Queries) DeleteMembershipsByDivisionSubtree(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembershipsByDivisionSubtree, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMembershipsByPosition = `-- name: DeleteMembershipsByPosition :execrows
DELETE FROM memberships WHERE position_id = $1
`

func (q *Queries) DeleteMembershipsByPosition(ctx context.Context, positionID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembershipsByPosition, positionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMembersByPosition = `-- name: ListMembersByPosition :many
SELECT
    m.user_id,
    m.position_id,
    p.title       AS position_title,
    p.role_id,
    r.name        AS role_name,
    p.division_id,
    p.is_archived AS position_archived,
    d.short_name  AS division_short_name,
    d.is_archived AS division_archived
FROM memberships m
JOIN users u ON u.id = m.user_id
JOIN positions p ON p.id = m.position_id
JOIN roles r ON r.id = p.role_id
JOIN divisions d ON d.id = p.division_id
WHERE m.position_id = $1
  AND p.is_archived = false
  AND d.is_archived = false
ORDER BY u.first_name ASC, u.id ASC, m.user_id ASC, m.position_id ASC
`

type ListMembersByPositionRow struct {
	UserID            string `json:"user_id"`
	PositionID        string `json:"position_id"`
	PositionTitle     string `json:"position_title"`
	RoleID            string `json:"role_id"`
	RoleName          string `json:"role_name"`
	DivisionID        string `json:"division_id"`
	PositionArchived  bool   `json:"position_archived"`
	DivisionShortName string `json:"division_short_name"`
	DivisionArchived  bool   `json:"division_archived"`
}

func (q *Queries) ListMembersByPosition(ctx context.Context, positionID string) ([]ListMembersByPositionRow, error) {
	rows, err := q.db.Query(ctx, listMembersByPosition, positionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByPositionRow
	for rows.Next() {
		var i ListMembersByPositionRow
		if err := rows.Scan(
			&i.UserID,
			&i.PositionID,
			&i.PositionTitle,
			&i.RoleID,
			&i.RoleName,
			&i.DivisionID,
			&i.PositionArchived,
			&i.DivisionShortName,
			&i.DivisionArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT
    m.user_id,
    m.position_id,
    p.title       AS position_title,
    p.role_id,
    r.name        AS role_name,
    p.division_id,
    p.is_archived AS position_archived,
    d.short_name  AS division_short_name,
    d.is_archived AS division_archived
FROM memberships m
JOIN positions p ON p.id = m.position_id
JOIN roles r ON r.id = p.role_id
JOIN divisions d ON d.id = p.division_id
WHERE m.user_id = $1
  AND p.is_archived = false
  AND d.is_archived = false
`

type ListMembershipsByUserRow struct {
	UserID            string `json:"user_id"`
	PositionID        string `json:"position_id"`
	PositionTitle     string `json:"position_title"`
	RoleID            string `json:"role_id"`
	RoleName          string `json:"role_name"`
	DivisionID        string `json:"division_id"`
	PositionArchived  bool   `json:"position_archived"`
	DivisionShortName string `json:"division_short_name"`
	DivisionArchived  bool   `json:"division_archived"`
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID string) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByUserRow
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.PositionID,
			&i.PositionTitle,
			&i.RoleID,
			&i.RoleName,
			&i.DivisionID,
			&i.PositionArchived,
			&i.DivisionShortName,
			&i.DivisionArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const membershipExists = `-- name: MembershipExists :one
SELECT exists(
    SELECT 1 FROM memberships WHERE user_id = $1 AND position_id = $2
)
`

type MembershipExistsParams struct {
	UserID     string `json:"user_id"`
	PositionID string `json:"position_id"`
}

func (q *Queries) MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipExists, arg.UserID, arg.PositionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
