// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Division struct {
	ID            string             `json:"id"`
	ParentID      pgtype.Text        `json:"parent_id"`
	ShortName     string             `json:"short_name"`
	FullName      string             `json:"full_name"`
	Description   string             `json:"description"`
	RegulationUrl string             `json:"regulation_url"`
	MediaLinks    []byte             `json:"media_links"`
	IsArchived    bool               `json:"is_archived"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type EventLog struct {
	ID          string             `json:"id"`
	EventType   string             `json:"event_type"`
	ActorID     string             `json:"actor_id"`
	SubjectType string             `json:"subject_type"`
	SubjectID   string             `json:"subject_id"`
	Payload     []byte             `json:"payload"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	UserID     string `json:"user_id"`
	PositionID string `json:"position_id"`
}

type Position struct {
	ID         string      `json:"id"`
	Title      string      `json:"title"`
	RoleID     string      `json:"role_id"`
	DivisionID string      `json:"division_id"`
	MaxCount   pgtype.Int4 `json:"max_count"`
	IsArchived bool        `json:"is_archived"`
}

type Role struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Permissions []byte             `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID                string             `json:"id"`
	UserID            string             `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	CsrfSecret        string             `json:"csrf_secret"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason     pgtype.Text        `json:"revoked_reason"`
	CreatedIp         string             `json:"created_ip"`
	CreatedUserAgent  string             `json:"created_user_agent"`
}

type User struct {
	ID              string             `json:"id"`
	Login           string             `json:"login"`
	PasswordHash    string             `json:"password_hash"`
	FirstName       string             `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	MiddleName      pgtype.Text        `json:"middle_name"`
	GradebookNumber pgtype.Text        `json:"gradebook_number"`
	GroupNumber     pgtype.Text        `json:"group_number"`
	Institute       pgtype.Text        `json:"institute"`
	BirthDate       pgtype.Date        `json:"birth_date"`
	Phone           pgtype.Text        `json:"phone"`
	SocialLinks     []byte             `json:"social_links"`
	About           pgtype.Text        `json:"about"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
