// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: positions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePosition = `-- name: ArchivePosition :one
UPDATE positions SET is_archived = true WHERE id = $1
RETURNING id, title, role_id, division_id, max_count, is_archived
`

func (q *Queries) ArchivePosition(ctx context.Context, id string) (Position, error) {
	row := q.db.QueryRow(ctx, archivePosition, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.RoleID,
		&i.DivisionID,
		&i.MaxCount,
		&i.IsArchived,
	)
	return i, err
}

const archivePositionsByDivisionSubtree = `-- name: ArchivePositionsByDivisionSubtree :execrows
WITH RECURSIVE subtree AS (
    SELECT d.id
    FROM divisions d
    WHERE d.id = $1
  UNION ALL
    SELECT d.id
    FROM divisions d
    JOIN subtree s ON d.parent_id = s.id
)
UPDATE positions
SET is_archived = true
WHERE division_id IN (SELECT id FROM subtree)
  AND is_archived = false
`

func (q *Queries) ArchivePositionsByDivisionSubtree(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, archivePositionsByDivisionSubtree, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMembersByPosition = `-- name: CountMembersByPosition :one
SELECT count(*) FROM memberships WHERE position_id = $1
`

func (q *Queries) CountMembersByPosition(ctx context.Context, positionID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByPosition, positionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (id, title, role_id, division_id, max_count, is_archived)
VALUES ($1, $2, $3, $4, $5, false)
RETURNING id, title, role_id, division_id, max_count, is_archived
`

type CreatePositionParams struct {
	ID         string      `json:"id"`
	Title      string      `json:"title"`
	RoleID     string      `json:"role_id"`
	DivisionID string      `json:"division_id"`
	MaxCount   pgtype.Int4 `json:"max_count"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.ID,
		arg.Title,
		arg.RoleID,
		arg.DivisionID,
		arg.MaxCount,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.RoleID,
		&i.DivisionID,
		&i.MaxCount,
		&i.IsArchived,
	)
	return i, err
}

const getPositionByID = `-- name: GetPositionByID :one
SELECT id, title, role_id, division_id, max_count, is_archived FROM positions WHERE id = $1
`

func (q *Queries) GetPositionByID(ctx context.Context, id string) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByID, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.RoleID,
		&i.DivisionID,
		&i.MaxCount,
		&i.IsArchived,
	)
	return i, err
}

const getPositionByIDForUpdate = `-- name: GetPositionByIDForUpdate :one
SELECT id, title, role_id, division_id, max_count, is_archived FROM positions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPositionByIDForUpdate(ctx context.Context, id string) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByIDForUpdate, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.RoleID,
		&i.DivisionID,
		&i.MaxCount,
		&i.IsArchived,
	)
	return i, err
}

const listPositionsByDivision = `-- name: ListPositionsByDivision :many
SELECT id, title, role_id, division_id, max_count, is_archived FROM positions WHERE division_id = $1 AND is_archived = false ORDER BY title
`

func (q *Queries) ListPositionsByDivision(ctx context.Context, divisionID string) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByDivision, divisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.RoleID,
			&i.DivisionID,
			&i.MaxCount,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions SET title = $2, role_id = $3, max_count = $4
WHERE id = $1
RETURNING id, title, role_id, division_id, max_count, is_archived
`

type UpdatePositionParams struct {
	ID       string      `json:"id"`
	Title    string      `json:"title"`
	RoleID   string      `json:"role_id"`
	MaxCount pgtype.Int4 `json:"max_count"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.ID,
		arg.Title,
		arg.RoleID,
		arg.MaxCount,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.RoleID,
		&i.DivisionID,
		&i.MaxCount,
		&i.IsArchived,
	)
	return i, err
}
