// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveChildDivisionsByRoot(ctx context.Context, id string) (int64, error)
	ArchiveDivisionByID(ctx context.Context, id string) (int64, error)
	ArchivePosition(ctx context.Context, id string) (Position, error)
	ArchivePositionsByDivisionSubtree(ctx context.Context, id string) (int64, error)
	CountEventLog(ctx context.Context, arg CountEventLogParams) (int64, error)
	CountMembersByPosition(ctx context.Context, positionID string) (int64, error)
	CountRoles(ctx context.Context) (int64, error)
	CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error)
	CreateDivision(ctx context.Context, arg CreateDivisionParams) (Division, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context, absoluteExpiresAt pgtype.Timestamptz) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeleteMembershipsByDivisionSubtree(ctx context.Context, id string) (int64, error)
	DeleteMembershipsByPosition(ctx context.Context, positionID string) (int64, error)
	DeleteRole(ctx context.Context, id string) error
	GetDivisionAncestors(ctx context.Context, id string) ([]GetDivisionAncestorsRow, error)
	GetDivisionArchivedFlag(ctx context.Context, id string) (bool, error)
	GetDivisionByID(ctx context.Context, id string) (Division, error)
	GetPositionByID(ctx context.Context, id string) (Position, error)
	GetPositionByIDForUpdate(ctx context.Context, id string) (Position, error)
	GetRoleByID(ctx context.Context, id string) (Role, error)
	GetRootDivision(ctx context.Context) (Division, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	InsertEventLog(ctx context.Context, arg InsertEventLogParams) (EventLog, error)
	ListActiveDivisionIDsByUser(ctx context.Context, userID string) ([]string, error)
	ListDivisionChildrenByParent(ctx context.Context, parentID pgtype.Text) ([]ListDivisionChildrenByParentRow, error)
	ListDivisionSubtree(ctx context.Context, id string) ([]ListDivisionSubtreeRow, error)
	ListDivisionTree(ctx context.Context, includeArchived bool) ([]ListDivisionTreeRow, error)
	ListEventLog(ctx context.Context, arg ListEventLogParams) ([]EventLog, error)
	ListMembersByPosition(ctx context.Context, positionID string) ([]ListMembersByPositionRow, error)
	ListMembershipsByUser(ctx context.Context, userID string) ([]ListMembershipsByUserRow, error)
	ListPermissionContextsByUser(ctx context.Context, userID string) ([]ListPermissionContextsByUserRow, error)
	ListPositionsByDivision(ctx context.Context, divisionID string) ([]Position, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListRootDivisions(ctx context.Context) ([]ListRootDivisionsRow, error)
	MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error)
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int64, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) (Session, error)
	UpdateDivision(ctx context.Context, arg UpdateDivisionParams) (Division, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
