// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: search.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(DISTINCT u.id)
FROM users u
LEFT JOIN memberships m ON m.user_id = u.id
LEFT JOIN positions p ON p.id = m.position_id
LEFT JOIN roles r ON r.id = p.role_id
LEFT JOIN divisions d ON d.id = p.division_id
WHERE ($1::text IS NULL OR u.first_name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR u.last_name ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR u.middle_name ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL OR u.login ILIKE '%' || $4::text || '%')
  AND ($5::text IS NULL OR u.group_number ILIKE '%' || $5::text || '%')
  AND ($6::text IS NULL OR u.institute ILIKE '%' || $6::text || '%')
  AND ($7::text IS NULL OR u.about ILIKE '%' || $7::text || '%')
  AND ($8::text IS NULL OR p.title ILIKE '%' || $8::text || '%')
  AND ($9::text IS NULL OR r.name ILIKE '%' || $9::text || '%')
  AND (
    $10::bool
    OR p.id IS NULL
    OR (p.is_archived = false AND d.is_archived = false)
  )
`

type CountSearchUsersParams struct {
	FirstName       pgtype.Text `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	Login           pgtype.Text `json:"login"`
	GroupNumber     pgtype.Text `json:"group_number"`
	Institute       pgtype.Text `json:"institute"`
	About           pgtype.Text `json:"about"`
	PositionTitle   pgtype.Text `json:"position_title"`
	RoleName        pgtype.Text `json:"role_name"`
	IncludeArchived bool        `json:"include_archived"`
}

func (q *Queries) CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Login,
		arg.GroupNumber,
		arg.Institute,
		arg.About,
		arg.PositionTitle,
		arg.RoleName,
		arg.IncludeArchived,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT DISTINCT
    u.id,
    u.first_name,
    u.last_name,
    u.middle_name,
    u.login,
    u.group_number,
    u.institute,
    u.about,
    u.phone,
    u.social_links,
    u.birth_date,
    u.gradebook_number
FROM users u
LEFT JOIN memberships m ON m.user_id = u.id
LEFT JOIN positions p ON p.id = m.position_id
LEFT JOIN roles r ON r.id = p.role_id
LEFT JOIN divisions d ON d.id = p.division_id
WHERE ($1::text IS NULL OR u.first_name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR u.last_name ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR u.middle_name ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL OR u.login ILIKE '%' || $4::text || '%')
  AND ($5::text IS NULL OR u.group_number ILIKE '%' || $5::text || '%')
  AND ($6::text IS NULL OR u.institute ILIKE '%' || $6::text || '%')
  AND ($7::text IS NULL OR u.about ILIKE '%' || $7::text || '%')
  AND ($8::text IS NULL OR p.title ILIKE '%' || $8::text || '%')
  AND ($9::text IS NULL OR r.name ILIKE '%' || $9::text || '%')
  AND (
    $10::bool
    OR p.id IS NULL
    OR (p.is_archived = false AND d.is_archived = false)
  )
ORDER BY u.last_name, u.first_name, u.id
LIMIT $12::int
OFFSET $11::int
`

type SearchUsersParams struct {
	FirstName       pgtype.Text `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	Login           pgtype.Text `json:"login"`
	GroupNumber     pgtype.Text `json:"group_number"`
	Institute       pgtype.Text `json:"institute"`
	About           pgtype.Text `json:"about"`
	PositionTitle   pgtype.Text `json:"position_title"`
	RoleName        pgtype.Text `json:"role_name"`
	IncludeArchived bool        `json:"include_archived"`
	PageOffset      int32       `json:"page_offset"`
	PageLimit       int32       `json:"page_limit"`
}

type SearchUsersRow struct {
	ID              string      `json:"id"`
	FirstName       string      `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	Login           string      `json:"login"`
	GroupNumber     pgtype.Text `json:"group_number"`
	Institute       pgtype.Text `json:"institute"`
	About           pgtype.Text `json:"about"`
	Phone           pgtype.Text `json:"phone"`
	SocialLinks     []byte      `json:"social_links"`
	BirthDate       pgtype.Date `json:"birth_date"`
	GradebookNumber pgtype.Text `json:"gradebook_number"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Login,
		arg.GroupNumber,
		arg.Institute,
		arg.About,
		arg.PositionTitle,
		arg.RoleName,
		arg.IncludeArchived,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Login,
			&i.GroupNumber,
			&i.Institute,
			&i.About,
			&i.Phone,
			&i.SocialLinks,
			&i.BirthDate,
			&i.GradebookNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
