// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id,
    token_hash,
    csrf_secret,
    absolute_expires_at,
    idle_expires_at,
    created_ip,
    created_user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id,
    user_id,
    token_hash,
    csrf_secret,
    created_at,
    last_seen_at,
    absolute_expires_at,
    idle_expires_at,
    revoked_at,
    revoked_reason,
    created_ip,
    created_user_agent
`

type CreateSessionParams struct {
	ID                string             `json:"id"`
	UserID            string             `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	CsrfSecret        string             `json:"csrf_secret"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	CreatedIp         string             `json:"created_ip"`
	CreatedUserAgent  string             `json:"created_user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfSecret,
		arg.AbsoluteExpiresAt,
		arg.IdleExpiresAt,
		arg.CreatedIp,
		arg.CreatedUserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedIp,
		&i.CreatedUserAgent,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE absolute_expires_at <= $1
   OR idle_expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, absoluteExpiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, absoluteExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    id,
    user_id,
    token_hash,
    csrf_secret,
    created_at,
    last_seen_at,
    absolute_expires_at,
    idle_expires_at,
    revoked_at,
    revoked_reason,
    created_ip,
    created_user_agent
FROM sessions
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedIp,
		&i.CreatedUserAgent,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE sessions
SET
    revoked_at = $2,
    revoked_reason = $3
WHERE user_id = $1
  AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	UserID        string             `json:"user_id"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, arg.UserID, arg.RevokedAt, arg.RevokedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET
    revoked_at = $2,
    revoked_reason = $3
WHERE id = $1
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID            string             `json:"id"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt, arg.RevokedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions
SET
    last_seen_at = $2,
    idle_expires_at = $3
WHERE id = $1
  AND revoked_at IS NULL
RETURNING
    id,
    user_id,
    token_hash,
    csrf_secret,
    created_at,
    last_seen_at,
    absolute_expires_at,
    idle_expires_at,
    revoked_at,
    revoked_reason,
    created_ip,
    created_user_agent
`

type TouchSessionParams struct {
	ID            string             `json:"id"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	IdleExpiresAt pgtype.Timestamptz `json:"idle_expires_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.ID, arg.LastSeenAt, arg.IdleExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedIp,
		&i.CreatedUserAgent,
	)
	return i, err
}
