// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    login,
    password_hash,
    first_name,
    last_name,
    middle_name,
    gradebook_number,
    group_number,
    institute,
    birth_date,
    phone,
    social_links,
    about
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING
    id,
    login,
    password_hash,
    first_name,
    last_name,
    middle_name,
    gradebook_number,
    group_number,
    institute,
    birth_date,
    phone,
    social_links,
    about,
    created_at,
    updated_at
`

type CreateUserParams struct {
	ID              string      `json:"id"`
	Login           string      `json:"login"`
	PasswordHash    string      `json:"password_hash"`
	FirstName       string      `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	GradebookNumber pgtype.Text `json:"gradebook_number"`
	GroupNumber     pgtype.Text `json:"group_number"`
	Institute       pgtype.Text `json:"institute"`
	BirthDate       pgtype.Date `json:"birth_date"`
	Phone           pgtype.Text `json:"phone"`
	SocialLinks     []byte      `json:"social_links"`
	About           pgtype.Text `json:"about"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Login,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.GradebookNumber,
		arg.GroupNumber,
		arg.Institute,
		arg.BirthDate,
		arg.Phone,
		arg.SocialLinks,
		arg.About,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.GradebookNumber,
		&i.GroupNumber,
		&i.Institute,
		&i.BirthDate,
		&i.Phone,
		&i.SocialLinks,
		&i.About,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    login,
    password_hash,
    first_name,
    last_name,
    middle_name,
    gradebook_number,
    group_number,
    institute,
    birth_date,
    phone,
    social_links,
    about,
    created_at,
    updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.GradebookNumber,
		&i.GroupNumber,
		&i.Institute,
		&i.BirthDate,
		&i.Phone,
		&i.SocialLinks,
		&i.About,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT
    id,
    login,
    password_hash,
    first_name,
    last_name,
    middle_name,
    gradebook_number,
    group_number,
    institute,
    birth_date,
    phone,
    social_links,
    about,
    created_at,
    updated_at
FROM users
WHERE login = $1
LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.GradebookNumber,
		&i.GroupNumber,
		&i.Institute,
		&i.BirthDate,
		&i.Phone,
		&i.SocialLinks,
		&i.About,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    first_name = $2,
    last_name = $3,
    middle_name = $4,
    gradebook_number = $5,
    group_number = $6,
    institute = $7,
    birth_date = $8,
    phone = $9,
    social_links = $10,
    about = $11,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    login,
    password_hash,
    first_name,
    last_name,
    middle_name,
    gradebook_number,
    group_number,
    institute,
    birth_date,
    phone,
    social_links,
    about,
    created_at,
    updated_at
`

type UpdateUserProfileParams struct {
	ID              string      `json:"id"`
	FirstName       string      `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	GradebookNumber pgtype.Text `json:"gradebook_number"`
	GroupNumber     pgtype.Text `json:"group_number"`
	Institute       pgtype.Text `json:"institute"`
	BirthDate       pgtype.Date `json:"birth_date"`
	Phone           pgtype.Text `json:"phone"`
	SocialLinks     []byte      `json:"social_links"`
	About           pgtype.Text `json:"about"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.GradebookNumber,
		arg.GroupNumber,
		arg.Institute,
		arg.BirthDate,
		arg.Phone,
		arg.SocialLinks,
		arg.About,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.GradebookNumber,
		&i.GroupNumber,
		&i.Institute,
		&i.BirthDate,
		&i.Phone,
		&i.SocialLinks,
		&i.About,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
